-- Rules Table Schema
create table if not exists public.rules (
  id text primary key,
  category text,
  description text,
  type text,
  severity text,
  requirements jsonb
);

-- Enable RLS
alter table public.rules enable row level security;
create policy "Allow public read access" on public.rules for select using (true);

-- Insert Rules
insert into public.rules (id, category, description, type, severity, requirements) values
('1', 'General', 'Ensure application of DGA Design System v1.0 (Platform Code).', 'automated', 'high', '["Verify that the version 1.0 of the Unified Design System is applied."]'::jsonb),
('2', 'Colors', 'Ensure use of approved colors and Color Design Tokens.', 'automated', 'high', '["Use Color Design Tokens (Backgrounds, Fonts, etc.) without modification.","Ensure contrast and clarity on colored backgrounds using the \"On Color\" property."]'::jsonb),
('3', 'Typography', 'Ensure use of approved fonts and Typography Design Tokens.', 'automated', 'high', '["Use the approved font \"IBM Plex Sans Arabic\".","Apply correct Typography Design Tokens for Display and Text variables."]'::jsonb),
('4', 'Spacing', 'Ensure application of spacing units and Global Spacing Design Tokens.', 'automated', 'medium', '["Adhere to approved spacing units (4px, 8px, 16px...).","Use Global Spacing Design Tokens; do not use custom spacing."]'::jsonb),
('5', 'Responsiveness', 'Ensure design adapts effectively to different screen sizes.', 'automated', 'high', '["Design must automatically rearrange columns/components for Mobile, Tablet, and Desktop.","Ensure full usability on mobile (touch interactions, viewport, navigation)."]'::jsonb),
('6', 'Icons', 'Ensure use of approved icons from the platform code library.', 'automated', 'medium', '["Use library icons without modification in size or color.","Use Alert colors (Success, Fail, Warn, Info) ONLY for alerts.","Use Neutral/Primary colors for general icons.","Use \"Featured icon\" for sizes > 24px.","Request approval for new icons if not found in library."]'::jsonb),
('7', 'Templates', 'Ensure Homepage template application matches the platform type.', 'automated', 'medium', '["Main Section: Use approved type (Image, Color Background, or Object).","Informational Platform: News/Info section must be first.","Service Platform: Services section must be first.","Partners Section: Follow platform code.","New Sections: Use approved foundations (Colors, Fonts, Buttons)."]'::jsonb),
('8', 'Templates', 'Ensure Service Page template application.', 'automated', 'medium', '["Full adherence to template (Steps, Conditions, Documents, Service Card).","Use Rating component exactly as in platform code.","Use Feedback component exactly as in platform code."]'::jsonb),
('9', 'Templates', 'Ensure E-Participation template application.', 'automated', 'medium', '["Adhere to the 8-section template.","Use links in sections if subpages do not exist."]'::jsonb),
('10', 'Templates', 'Ensure Search template application.', 'automated', 'medium', '["Adhere to Search template.","Search bar must be present in results page.","Results must be organized by category (News, Services, etc.).","Allow filtering by criteria (Content type, Date)."]'::jsonb),
('11', 'Components', 'Ensure Digital Stamp application.', 'automated', 'high', '["Place stamp at the top of the page.","Link stamp to its certificate page.","Max 2 secondary elements (share/accessibility) allowed on the left."]'::jsonb),
('12', 'Components', 'Ensure Button component compliance.', 'automated', 'high', '["Use standard Shape, Radius, Color, Spacing.","Implement all states: Default, Hovered, Pressed, Selected, Focused, Disabled."]'::jsonb),
('13', 'Components', 'Ensure Dropdown Menu compliance.', 'automated', 'medium', '["Use standard Shape, Radius, Color, Spacing.","Implement all states: Default, Hovered, Pressed, Focused, Read-only, Disabled.","Only List Items can be increased."]'::jsonb),
('14', 'Components', 'Ensure Link component compliance.', 'automated', 'medium', '["Use standard Shape, Radius, Color, Spacing.","Implement all states: Default, Hovered, Pressed, Focused, Visited, Disabled.","External links must have an \"External link\" icon."]'::jsonb),
('15', 'Components', 'Ensure Accordion component compliance.', 'automated', 'medium', '["Use standard Shape, Radius, Color, Spacing.","Implement states: Default, Hovered, Pressed, Focused, Disabled.","Implement Contextual states: Expanded / Collapsed."]'::jsonb),
('16', 'Components', 'Ensure Menu component compliance.', 'automated', 'medium', '["Use standard Shape, Radius, Color, Spacing.","Implement states: Default, Hovered, Pressed, Focused, Disabled.","Implement Contextual state: Selected."]'::jsonb),
('17', 'Components', 'Ensure Content Switcher compliance.', 'automated', 'medium', '["Use standard Shape, Radius, Color, Spacing.","Implement states: Normal, Hovered, Focused.","Implement Contextual state: Selected."]'::jsonb),
('18', 'Components', 'Ensure Notifications/Alerts compliance.', 'automated', 'medium', '["Use standard Shape, Radius, Color, Spacing.","Temporary: Use Notification Toast.","Permanent: Use Inline Alert.","High Priority Permanent: Use Notification at top of page.","Use correct context (e.g., Success for success).","Implement dismissible behavior where recommended."]'::jsonb),
('19', 'Components', 'Ensure Pop-up/Modal compliance.', 'automated', 'medium', '["Use standard Shape, Radius, Color, Spacing.","Use for confirmation, feedback, or alerts.","Do NOT use for large data entry (use Form template instead)."]'::jsonb),
('20', 'Components', 'Ensure File Upload component compliance.', 'automated', 'medium', '["Use standard Shape, Radius, Color, Spacing.","Implement states: Default, Drag+hover, Disabled.","Implement Contextual states: Uploaded / Not Uploaded.","Show file name, type, status (loading/done/fail), and remove option.","Clear error messages for size/type limits."]'::jsonb),
('21', 'Components', 'Ensure Checkbox component compliance.', 'automated', 'medium', '["Use standard Shape, Radius, Color, Spacing.","Implement states: Default, Hovered, Focused, Read-only, Disabled.","Implement Contextual states: Checked / Unchecked / Indeterminate."]'::jsonb),
('22', 'Components', 'Ensure Radio Button component compliance.', 'automated', 'medium', '["Use standard Shape, Radius, Color, Spacing.","Implement states: Default, Hovered, Focused, Read-only, Disabled.","Implement Contextual states: Selected / Unselected."]'::jsonb),
('23', 'Components', 'Ensure Toggle Switch compliance.', 'automated', 'medium', '["Use standard Shape, Radius, Color, Spacing.","Implement states: Default, Hovered, Focused, Disabled.","Implement Contextual states: On / Off."]'::jsonb),
('24', 'Components', 'Ensure Text Area compliance.', 'automated', 'medium', '["Use standard Shape, Radius, Color, Spacing.","Implement states: Default, Hovered, Pressed, Focused, Read-only, Disabled.","Support Placeholders, Helper text, and Error messages."]'::jsonb),
('25', 'Components', 'Ensure Tabs component compliance.', 'automated', 'medium', '["Use standard Shape, Radius, Color, Spacing.","Implement states: Default, Hovered, Focused, Disabled.","Implement Contextual states: Selected / Unselected.","Ensure clear text and visual balance."]'::jsonb),
('26', 'Components', 'Ensure Tags/Badges compliance.', 'automated', 'medium', '["Use standard Shape, Radius, Color, Spacing.","Alerts: Use Alert colors (Success, Fail, Warn, Info).","Classification: Use Neutral or Primary colors."]'::jsonb),
('27', 'Components', 'Ensure Footer compliance.', 'automated', 'high', '["Use standard Shape, Radius, Color, Spacing.","Group links (e.g., Important Links, Support).","Include mandatory elements: Official Links, Logos, Contact, Privacy Policy."]'::jsonb),
('28', 'Components', 'Ensure Card component compliance.', 'automated', 'medium', '["Use standard Shape, Radius, Color, Spacing.","Implement states: Default, Hover, Focused, Disabled.","Allowed changes: Alignment and Spacing only.","Use approved variants (Content, Image, Shadow...).","Actionable cards must have CTA buttons."]'::jsonb),
('29', 'Components', 'Ensure Top Navigation Bar compliance.', 'automated', 'high', '["Use standard Shape, Radius, Color, Spacing.","Implement states: Default, Hovered, Pressed, Focused, Disabled.","Implement Contextual state: Selected.","Ensure responsiveness.","External links in nav must have \"External link\" icon."]'::jsonb),
('30', 'Components', 'Ensure Breadcrumb compliance.', 'automated', 'medium', '["Use standard Shape, Radius, Color, Spacing.","Implement states: Default, Hovered, Pressed, Focused, Disabled.","Current page must be Disabled (not clickable).","Consistent with site hierarchy."]'::jsonb),
('31', 'Components', 'Ensure Avatar component compliance.', 'automated', 'medium', '["Use standard Shape, Radius, Color, Spacing.","Adhere to 3 contexts: Initials, Image, or Icon."]'::jsonb),
('32', 'Components', 'Ensure Rating component compliance.', 'automated', 'medium', '["Use standard Shape, Radius, Color, Spacing.","Implement states: Normal, Pressed.","Implement Contextual states: Selected, Half."]'::jsonb),
('33', 'Components', 'Ensure Tooltip compliance.', 'automated', 'medium', '["Use standard Shape, Radius, Color, Spacing.","Adhere to positioning: Top/Bottom/Right/Left and Start/Center/End."]'::jsonb),
('34', 'Components', 'Ensure Input Fields compliance.', 'automated', 'high', '["Use standard Shape, Radius, Color, Spacing.","Implement states: Default, Hovered, Pressed, Focused, Read-only, Disabled.","Support Placeholders, Helper text, and Error messages."]'::jsonb),
('35', 'Components', 'Ensure Table component compliance.', 'automated', 'medium', '["Use standard Shape, Radius, Color, Spacing."]'::jsonb),
('36', 'Components', 'Ensure Date Picker compliance.', 'automated', 'medium', '["Use standard Shape, Radius, Color, Spacing.","Implement states: Default, Hovered, Pressed, Focused, Disabled.","Implement Contextual states: Selected, Today, Next/Prev."]'::jsonb),
('37', 'UX', 'Ensure Sitemap creation to support navigation.', 'automated', 'medium', '["Gather main structure from Nav header, Footer, Breadcrumb.","Provide comprehensive and updated Sitemap."]'::jsonb),
('38', 'UX', 'Ensure effective interaction design.', 'manual', 'medium', '["Provide immediate visual feedback for interactions (buttons, links).","Support basic gestures (Swipe, Tap, Scroll) on touch devices.","Do NOT hide important elements behind hover/motion."]'::jsonb),
('39', 'Language', 'Ensure "Arabic First" approach.', 'automated', 'high', '["Arabic is the primary language.","Secondary languages supported.","Accurate translation without information loss."]'::jsonb),
('40', 'UX', 'Ensure user feedback mechanisms.', 'automated', 'medium', '["Provide clear way for users to give feedback.","Show confirmation message after feedback submission."]'::jsonb),
('41', 'Privacy', 'Ensure visibility and clarity of Privacy and Security notices.', 'automated', 'high', '["Notices must be clear and not hidden.","Provide links at interaction points (Login, Signup).","Place notices in familiar locations (Footer)."]'::jsonb),
('42', 'Content', 'Ensure consistency in terminology.', 'automated', 'medium', '["Use unified terms across all screens.","Follow approved language guide.","Avoid redundancy."]'::jsonb),
('43', 'UX', 'Ensure consistent error handling and display.', 'automated', 'high', '["Display errors with same visual/spatial style for same context.","Use clear, consistent wording.","Messages should be concise and helpful."]'::jsonb),
('44', 'Components', 'Ensure Side Navigation compliance.', 'automated', 'medium', '["Use standard Shape, Radius, Color, Spacing."]'::jsonb),
('45', 'Components', 'Ensure Pagination compliance.', 'automated', 'medium', '["Use standard Shape, Radius, Color, Spacing."]'::jsonb),
('46', 'Components', 'Ensure Loading Indicator compliance.', 'automated', 'medium', '["Use standard Shape, Radius, Color, Spacing."]'::jsonb),
('47', 'Components', 'Ensure Steps/Stepper compliance.', 'automated', 'medium', '["Use standard Shape, Radius, Color, Spacing."]'::jsonb),
('48', 'UX', 'Ensure clear visual hierarchy.', 'automated', 'medium', '["Design must direct user attention to important elements first."]'::jsonb),
('49', 'UX', 'Ensure intuitive navigation and grouping.', 'automated', 'medium', '["Navigation should be intuitive.","Logical grouping and labeling of sections."]'::jsonb),
('50', 'UX', 'Ensure common tasks can be completed efficiently.', 'automated', 'medium', '["Minimal steps for common tasks.","Intuitive interactions."]'::jsonb),
('51', 'UX', 'Ensure help resources and documentation are available.', 'automated', 'medium', '["Easy access to help/docs.","Clear and useful content."]'::jsonb),
('52', 'Content', 'Ensure language is clear, concise, and appropriate.', 'automated', 'medium', '["Language suitable for target audience.","Evaluate translation quality."]'::jsonb),
('53', 'UX', 'Ensure predictable UI behavior.', 'manual', 'medium', '["Interface behaves in a predictable way.","Reduce user confusion/errors."]'::jsonb),
('54', 'UX', 'Ensure consistent interaction patterns.', 'manual', 'medium', '["Consistent gestures, clicks, and navigation.","Make system learnable."]'::jsonb),
('55', 'Content', 'Ensure consistent content style and tone.', 'manual', 'medium', '["Unified style and tone across text, images, video."]'::jsonb),
('56', 'UX', 'Ensure consistent feedback for user actions.', 'manual', 'medium', '["Consistent style and timing for feedback."]'::jsonb);
